global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # ─ Custom prom‑client metrics on :4000/metrics ─
  - job_name: 'ansar-api'
    metrics_path: /metrics # default, but explicit is clearer
    static_configs:
      - targets: ['app:4000']
